---
football_club_domain: "mplytics.eu"
football_club_admin_email: "linards.kalvans@gmail.com"
football_club_project_dir: "/opt/fk-cesis"
football_club_backup_dir: "/opt/backups/fk-cesis"
football_club_backup_remote: "linards@192.168.3.249:/opt/backups/fk-cesis/"
football_club_timezone: "Europe/Riga"
football_club_caddyfile_path: "/etc/caddy/Caddyfile"
football_club_caddy_snippet_path: "/etc/caddy/football-club-routes.caddy"
football_club_caddy_backup_dir: "/etc/caddy/backups"
football_club_compose_project_name: "fk-cesis"
football_club_caddy_mode: "subdomain"
football_club_stack_mms_image_tag: "dev"
football_club_stack_mms_email_host_user: "linards.kalvans@gmail.com"
football_club_stack_mms_default_from_email: "linards.kalvans+fk-cesis@gmail.com"
football_club_stack_mms_superuser_email: "linards.kalvans@gmail.com"
football_club_stack_mms_superuser_username: "linards.kalvans"
football_club_manage_caddy: false
football_club_stack_mms_host_port: "8019"
football_club_stack_mms_allowed_hosts: "members.mplytics.eu,fkcesis.mplytics.eu"
football_club_stack_mms_csrf_trusted_origins: "https://members.mplytics.eu,https://fkcesis.mplytics.eu"
football_club_stack_mms_ocr_provider_mode: "tiny_idp"
