---
vault_ninja_app_key: "base64:change-me"
vault_ninja_admin_password: "change-me"
vault_ninja_db_password: "change-me"
vault_ninja_db_root_password: "change-me"
vault_docuseal_secret_key: "change-me-64-characters-minimum"
ansible_become_password: "your-sudo-password"
