---
dolibarr_url_root: >-
  {{ 'https://' ~ football_club_domain ~ '/club'
     if football_club_caddy_mode == 'path'
     else 'https://club.' ~ football_club_domain }}

invoiceninja_app_url: >-
  {{ 'https://' ~ football_club_domain ~ '/billing'
     if football_club_caddy_mode == 'path'
     else 'https://billing.' ~ football_club_domain }}

n8n_host: >-
  {{ football_club_domain
     if football_club_caddy_mode == 'path'
     else 'n8n.' ~ football_club_domain }}

n8n_webhook_url: >-
  {{ 'https://' ~ football_club_domain ~ '/n8n/'
     if football_club_caddy_mode == 'path'
     else 'https://n8n.' ~ football_club_domain ~ '/' }}
