---
vault_doli_db_password: "change-me"
vault_doli_db_root_password: "change-me"
vault_doli_admin_password: "change-me"
vault_ninja_app_key: "base64:change-me"
vault_ninja_admin_password: "change-me"
vault_ninja_db_password: "change-me"
vault_ninja_db_root_password: "change-me"
vault_n8n_encryption_key: "change-me-32-characters-minimum"
vault_n8n_db_password: "change-me"
vault_docuseal_secret_key: "change-me-64-characters-minimum"
vault_stripe_publishable_key: "pk_test_change_me"
vault_stripe_secret_key: "sk_test_change_me"
vault_stripe_webhook_secret: "whsec_change_me"
