---
vault_ninja_app_key: "base64:change-me"
vault_ninja_admin_password: "change-me"
vault_ninja_db_password: "change-me"
vault_ninja_db_root_password: "change-me"
vault_docuseal_secret_key: "change-me-64-characters-minimum"
vault_mms_django_secret_key: "change-me"
vault_mms_postgres_password: "change-me"
vault_mms_tiny_idp_api_key: ""
vault_mms_ocr_encryption_key: "change-me-fernet-key"
vault_mms_docuseal_api_key: "change-me"
vault_mms_docuseal_template_id: "change-me"
vault_mms_docuseal_webhook_secret: "change-me"
vault_mms_invoice_ninja_api_key: "change-me"
vault_mms_email_host_password: "change-me"
vault_mms_superuser_password: "change-me"
